psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=0 "-game=Shin Megami Tensei" -title=Demo -year=1992 "SHVC-ME-1-0093.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=6 "-game=Shin Megami Tensei" -title=Title -year=1992 "SHVC-ME-1-0094.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" -title=Dream -year=1992 "SHVC-ME-1-0082.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" -title=Home -year=1992 "SHVC-ME-1-0083.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" -title=Kichijoji -year=1992 "SHVC-ME-1-0078.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" -title=Arcade -year=1992 "SHVC-ME-1-0077.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" -title=Neutral -year=1992 "SHVC-ME-1-0071.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=6 "-game=Shin Megami Tensei" -title=Embassy -year=1992 "SHVC-ME-1-0076.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=6 "-game=Shin Megami Tensei" -title=Shop -year=1992 "SHVC-ME-1-0080.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" -title=Terminal -year=1992 "SHVC-ME-1-0087.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=7 "-game=Shin Megami Tensei" "-title=Castle of the Four Gods" -year=1992 "SHVC-ME-1-0075.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" "-title=Demon Appears" -year=1992 "SHVC-ME-1-0056.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" "-title=Demon Appears" -year=1992 "SHVC-ME-1-0057.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" "-title=Demon Appears" -year=1992 "SHVC-ME-1-0058.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" "-title=Demon Appears" -year=1992 "SHVC-ME-1-0059.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" "-title=Demon Appears" -year=1992 "SHVC-ME-1-0063.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" "-title=Demon Appears" -year=1992 "SHVC-ME-1-0066.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" "-title=Demon Appears" -year=1992 "SHVC-ME-1-0067.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" -title=Battle -year=1992 "SHVC-ME-1-0060.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" "-title=Level Up" -year=1992 "SHVC-ME-1-0061.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=9 "-game=Shin Megami Tensei" -title=Law -year=1992 "SHVC-ME-1-0069.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=6 "-game=Shin Megami Tensei" -title=Ginza -year=1992 "SHVC-ME-1-0072.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=10 "-game=Shin Megami Tensei" -title=Jakyou -year=1992 "SHVC-ME-1-0068.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=7 "-game=Shin Megami Tensei" -title=Fusion -year=1992 "SHVC-ME-1-0064.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" -title=Shibuya -year=1992 "SHVC-ME-1-0074.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=7 "-game=Shin Megami Tensei" "-title=Boss Battle" -year=1992 "SHVC-ME-1-0081.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" "-title=Game Over" -year=1992 "SHVC-ME-1-0086.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=6 "-game=Shin Megami Tensei" -title=Ruins -year=1992 "SHVC-ME-1-0079.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=8 "-game=Shin Megami Tensei" -title=Chaos -year=1992 "SHVC-ME-1-0070.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=9 "-game=Shin Megami Tensei" -title=Cathedral -year=1992 "SHVC-ME-1-0073.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=7 "-game=Shin Megami Tensei" -title=Epilogue -year=1992 "SHVC-ME-1-0088.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=0 "-game=Shin Megami Tensei" -title=Ending -year=1992 "SHVC-ME-1-0095.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=10 "-game=Shin Megami Tensei" "-title=Unknown Song" -year=1992 "SHVC-ME-1-0085.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=10 "-game=Shin Megami Tensei" "-title=Pascal's Theme" -year=1992 "SHVC-ME-1-0084.minisnsf"
psfpoint "-artist=Tsukasa Masuko" -copyright=Atlus -fade=0 "-game=Shin Megami Tensei" -title=Teleportation -year=1992 "SHVC-ME-1-0013.minisnsf"
